[package]
name = "notiva"
version = "0.1.0"
description = "Notiva - Visual Notes & Idea Workspace"
authors = ["Marvills"]
edition = "2021"
build = "build.rs"
[lib]
name = "notiva_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
[build-dependencies]
tauri-build = { version = "2", features = [] }
[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"