import {
  DrawingStickerCategoryDefinition,
  DrawingStickerDefinition,
} from '../models/drawing-sticker.model';
export const DRAWING_STICKER_CATEGORIES: DrawingStickerCategoryDefinition[] = [
  { id: 'all', name: 'All', icon: 'fa-solid fa-border-all' },
  { id: 'emoji', name: 'Emoji', icon: 'fa-regular fa-face-smile' },
  { id: 'reactions', name: 'Reactions', icon: 'fa-regular fa-face-laugh-beam' },
  { id: 'arrows', name: 'Arrows', icon: 'fa-solid fa-arrow-right' },
  { id: 'symbols', name: 'Symbols', icon: 'fa-solid fa-icons' },
  { id: 'shapes', name: 'Shapes', icon: 'fa-regular fa-square' },
  { id: 'stars', name: 'Stars', icon: 'fa-regular fa-star' },
  { id: 'hearts', name: 'Hearts', icon: 'fa-regular fa-heart' },
  { id: 'nature', name: 'Nature', icon: 'fa-solid fa-leaf' },
  { id: 'animals', name: 'Animals', icon: 'fa-solid fa-paw' },
  { id: 'food', name: 'Food', icon: 'fa-solid fa-utensils' },
  { id: 'work', name: 'Work', icon: 'fa-solid fa-briefcase' },
  { id: 'school', name: 'School', icon: 'fa-solid fa-graduation-cap' },
  { id: 'tech', name: 'Tech', icon: 'fa-solid fa-laptop-code' },
  { id: 'travel', name: 'Travel', icon: 'fa-solid fa-plane' },
  { id: 'weather', name: 'Weather', icon: 'fa-solid fa-cloud-sun' },
  { id: 'labels', name: 'Labels', icon: 'fa-solid fa-tag' },
  { id: 'pins', name: 'Pins', icon: 'fa-solid fa-thumbtack' },
  { id: 'tape', name: 'Tape', icon: 'fa-solid fa-tape' },
  { id: 'doodles', name: 'Doodles', icon: 'fa-solid fa-pencil' },
];
const emoji = (
  id: string,
  name: string,
  value: string,
  keywords: string[] = [],
): DrawingStickerDefinition => ({
  id,
  type: 'emoji',
  category: 'emoji',
  name,
  value,
  keywords: [name.toLowerCase(), ...keywords],
  defaultWidth: 64,
  defaultHeight: 64,
});
const reaction = (
  id: string,
  name: string,
  value: string,
  keywords: string[] = [],
): DrawingStickerDefinition => ({
  id,
  type: 'emoji',
  category: 'reactions',
  name,
  value,
  keywords: [name.toLowerCase(), ...keywords],
  defaultWidth: 64,
  defaultHeight: 64,
});
const sticker = (
  id: string,
  category: DrawingStickerDefinition['category'],
  name: string,
  value: string,
  keywords: string[] = [],
  width = 64,
  height = 64,
  boardTypes?: string[],
): DrawingStickerDefinition => ({
  id,
  type:
    category === 'arrows' ||
    category === 'symbols' ||
    category === 'shapes' ||
    category === 'stars' ||
    category === 'hearts'
      ? 'symbol'
      : 'sticker',
  category,
  name,
  value,
  keywords: [name.toLowerCase(), ...keywords],
  defaultWidth: width,
  defaultHeight: height,
  boardTypes,
});
export const DRAWING_STICKERS: DrawingStickerDefinition[] = [
  emoji('emoji-smile', 'Smile', '😀', ['happy', 'face']),
  emoji('emoji-grin', 'Grinning', '😁', ['happy', 'teeth']),
  emoji('emoji-laugh', 'Laughing', '😂', ['funny', 'joy']),
  emoji('emoji-rofl', 'Rolling Laugh', '🤣', ['funny', 'laugh']),
  emoji('emoji-sweat-smile', 'Sweat Smile', '😅', ['relief']),
  emoji('emoji-wink', 'Wink', '😉', ['face']),
  emoji('emoji-blush', 'Blush', '😊', ['happy']),
  emoji('emoji-heart-eyes', 'Heart Eyes', '😍', ['love']),
  emoji('emoji-stars-eyes', 'Star Eyes', '🤩', ['wow', 'excited']),
  emoji('emoji-kiss', 'Kiss', '😘', ['love']),
  emoji('emoji-tongue', 'Tongue', '😛', ['fun']),
  emoji('emoji-cool', 'Cool', '😎', ['sunglasses']),
  emoji('emoji-thinking', 'Thinking', '🤔', ['question', 'idea']),
  emoji('emoji-neutral', 'Neutral', '😐', ['face']),
  emoji('emoji-unamused', 'Unamused', '😒', ['face']),
  emoji('emoji-eye-roll', 'Eye Roll', '🙄', ['face']),
  emoji('emoji-sad', 'Sad', '😢', ['cry']),
  emoji('emoji-cry', 'Crying', '😭', ['sad']),
  emoji('emoji-angry', 'Angry', '😡', ['mad']),
  emoji('emoji-shocked', 'Shocked', '😱', ['surprise']),
  emoji('emoji-mind-blown', 'Mind Blown', '🤯', ['wow', 'idea']),
  emoji('emoji-party', 'Party', '🥳', ['celebrate']),
  emoji('emoji-sleep', 'Sleeping', '😴', ['tired']),
  emoji('emoji-sick', 'Sick', '🤒', ['ill']),
  emoji('emoji-nerd', 'Nerd', '🤓', ['smart', 'study']),
  emoji('emoji-monocle', 'Monocle', '🧐', ['inspect']),
  emoji('emoji-cowboy', 'Cowboy', '🤠', ['fun']),
  emoji('emoji-angel', 'Angel', '😇', ['good']),
  emoji('emoji-devil', 'Devil', '😈', ['mischief']),
  emoji('emoji-clown', 'Clown', '🤡', ['funny']),
  reaction('reaction-thumbs-up', 'Thumbs Up', '👍', ['yes', 'good', 'like']),
  reaction('reaction-thumbs-down', 'Thumbs Down', '👎', ['no', 'bad']),
  reaction('reaction-clap', 'Clap', '👏', ['applause', 'good']),
  reaction('reaction-hands', 'Raised Hands', '🙌', ['celebrate']),
  reaction('reaction-pray', 'Pray', '🙏', ['thanks', 'please']),
  reaction('reaction-muscle', 'Strong', '💪', ['power', 'fitness']),
  reaction('reaction-ok', 'OK', '👌', ['good']),
  reaction('reaction-victory', 'Victory', '✌️', ['peace']),
  reaction('reaction-crossed', 'Fingers Crossed', '🤞', ['hope', 'luck']),
  reaction('reaction-point-up', 'Point Up', '☝️', ['up']),
  reaction('reaction-point-right', 'Point Right', '👉', ['right']),
  reaction('reaction-point-left', 'Point Left', '👈', ['left']),
  reaction('reaction-point-down', 'Point Down', '👇', ['down']),
  reaction('reaction-wave', 'Wave', '👋', ['hello', 'bye']),
  reaction('reaction-fist', 'Fist', '✊', ['power']),
  reaction('reaction-handshake', 'Handshake', '🤝', ['agreement', 'work']),
  reaction('reaction-eyes', 'Eyes', '👀', ['look', 'watch']),
  reaction('reaction-brain', 'Brain', '🧠', ['think', 'idea']),
  reaction('reaction-fire', 'Fire', '🔥', ['hot', 'important']),
  reaction('reaction-hundred', 'Hundred', '💯', ['perfect']),
  reaction('reaction-boom', 'Boom', '💥', ['impact']),
  reaction('reaction-sparkles', 'Sparkles', '✨', ['shine', 'magic']),
  reaction('reaction-confetti', 'Confetti', '🎉', ['party', 'celebrate']),
  reaction('reaction-trophy', 'Trophy', '🏆', ['winner', 'success']),
  sticker('arrow-right', 'arrows', 'Right Arrow', '→', ['direction', 'next']),
  sticker('arrow-left', 'arrows', 'Left Arrow', '←', ['direction', 'back']),
  sticker('arrow-up', 'arrows', 'Up Arrow', '↑', ['direction']),
  sticker('arrow-down', 'arrows', 'Down Arrow', '↓', ['direction']),
  sticker('arrow-ne', 'arrows', 'Up Right Arrow', '↗', ['direction']),
  sticker('arrow-se', 'arrows', 'Down Right Arrow', '↘', ['direction']),
  sticker('arrow-sw', 'arrows', 'Down Left Arrow', '↙', ['direction']),
  sticker('arrow-nw', 'arrows', 'Up Left Arrow', '↖', ['direction']),
  sticker('arrow-double-right', 'arrows', 'Double Right', '⇒', ['direction']),
  sticker('arrow-double-left', 'arrows', 'Double Left', '⇐', ['direction']),
  sticker('arrow-curved', 'arrows', 'Curved Arrow', '↪', ['direction', 'turn']),
  sticker('arrow-return', 'arrows', 'Return Arrow', '↩', ['direction', 'return']),
  sticker('arrow-cycle', 'arrows', 'Cycle', '↻', ['rotate', 'refresh']),
  sticker('arrow-cycle-left', 'arrows', 'Cycle Left', '↺', ['rotate']),
  sticker('arrow-bold-right', 'arrows', 'Bold Right', '➜', ['direction']),
  sticker('arrow-point-right', 'arrows', 'Point Right', '➤', ['direction']),
  sticker('arrow-long-right', 'arrows', 'Long Right', '⟶', ['direction']),
  sticker('arrow-long-left', 'arrows', 'Long Left', '⟵', ['direction']),
  sticker('symbol-check', 'symbols', 'Check', '✓', ['yes', 'done', 'complete']),
  sticker('symbol-cross', 'symbols', 'Cross', '✕', ['no', 'remove']),
  sticker('symbol-warning', 'symbols', 'Warning', '⚠️', ['alert', 'important']),
  sticker('symbol-info', 'symbols', 'Information', 'ℹ️', ['info']),
  sticker('symbol-question', 'symbols', 'Question', '❓', ['help']),
  sticker('symbol-exclamation', 'symbols', 'Exclamation', '❗', ['important']),
  sticker('symbol-plus', 'symbols', 'Plus', '＋', ['add']),
  sticker('symbol-minus', 'symbols', 'Minus', '−', ['remove']),
  sticker('symbol-infinity', 'symbols', 'Infinity', '∞', ['forever']),
  sticker('symbol-copyright', 'symbols', 'Copyright', '©', ['copyright']),
  sticker('symbol-registered', 'symbols', 'Registered', '®', ['registered']),
  sticker('symbol-trademark', 'symbols', 'Trademark', '™', ['trademark']),
  sticker('symbol-peace', 'symbols', 'Peace', '☮', ['peace']),
  sticker('symbol-yinyang', 'symbols', 'Yin Yang', '☯', ['balance']),
  sticker('symbol-music', 'symbols', 'Music', '♫', ['song', 'audio']),
  sticker('symbol-lightning', 'symbols', 'Lightning', 'ϟ', ['power', 'energy']),
  sticker('shape-circle', 'shapes', 'Circle', '●', ['round']),
  sticker('shape-circle-outline', 'shapes', 'Circle Outline', '○', ['round']),
  sticker('shape-square', 'shapes', 'Square', '■', ['box']),
  sticker('shape-square-outline', 'shapes', 'Square Outline', '□', ['box']),
  sticker('shape-diamond', 'shapes', 'Diamond', '◆', ['rhombus']),
  sticker('shape-diamond-outline', 'shapes', 'Diamond Outline', '◇', ['rhombus']),
  sticker('shape-triangle', 'shapes', 'Triangle', '▲', ['triangle']),
  sticker('shape-triangle-down', 'shapes', 'Down Triangle', '▼', ['triangle']),
  sticker('shape-triangle-right', 'shapes', 'Right Triangle', '▶', ['play']),
  sticker('shape-triangle-left', 'shapes', 'Left Triangle', '◀', ['back']),
  sticker('shape-bullseye', 'shapes', 'Bullseye', '◎', ['target']),
  sticker('shape-target', 'shapes', 'Target', '🎯', ['goal']),
  sticker('star-yellow', 'stars', 'Yellow Star', '⭐', ['favorite']),
  sticker('star-glow', 'stars', 'Glowing Star', '🌟', ['shine']),
  sticker('star-sparkle', 'stars', 'Sparkling Star', '💫', ['magic']),
  sticker('star-outline', 'stars', 'Outline Star', '☆', ['favorite']),
  sticker('star-solid', 'stars', 'Solid Star', '★', ['favorite']),
  sticker('star-four', 'stars', 'Four Point Star', '✦', ['sparkle']),
  sticker('star-four-outline', 'stars', 'Four Point Outline', '✧', ['sparkle']),
  sticker('star-asterisk', 'stars', 'Asterisk Star', '✱', ['spark']),
  sticker('heart-red', 'hearts', 'Red Heart', '❤️', ['love']),
  sticker('heart-orange', 'hearts', 'Orange Heart', '🧡', ['love']),
  sticker('heart-yellow', 'hearts', 'Yellow Heart', '💛', ['love']),
  sticker('heart-green', 'hearts', 'Green Heart', '💚', ['love']),
  sticker('heart-blue', 'hearts', 'Blue Heart', '💙', ['love']),
  sticker('heart-purple', 'hearts', 'Purple Heart', '💜', ['love']),
  sticker('heart-black', 'hearts', 'Black Heart', '🖤', ['love']),
  sticker('heart-white', 'hearts', 'White Heart', '🤍', ['love']),
  sticker('heart-broken', 'hearts', 'Broken Heart', '💔', ['sad']),
  sticker('heart-sparkle', 'hearts', 'Sparkling Heart', '💖', ['love', 'sparkle']),
  sticker('nature-sun', 'nature', 'Sun', '☀️', ['weather', 'summer']),
  sticker('nature-moon', 'nature', 'Moon', '🌙', ['night']),
  sticker('nature-rainbow', 'nature', 'Rainbow', '🌈', ['weather']),
  sticker('nature-flower', 'nature', 'Flower', '🌸', ['spring']),
  sticker('nature-sunflower', 'nature', 'Sunflower', '🌻', ['flower']),
  sticker('nature-rose', 'nature', 'Rose', '🌹', ['flower']),
  sticker('nature-leaf', 'nature', 'Leaf', '🍃', ['green']),
  sticker('nature-maple', 'nature', 'Maple Leaf', '🍁', ['autumn']),
  sticker('nature-tree', 'nature', 'Tree', '🌳', ['forest']),
  sticker('nature-palm', 'nature', 'Palm Tree', '🌴', ['tropical']),
  sticker('nature-cactus', 'nature', 'Cactus', '🌵', ['desert']),
  sticker('nature-mushroom', 'nature', 'Mushroom', '🍄', ['forest']),
  sticker('animal-cat', 'animals', 'Cat', '🐱', ['pet']),
  sticker('animal-dog', 'animals', 'Dog', '🐶', ['pet']),
  sticker('animal-rabbit', 'animals', 'Rabbit', '🐰', ['pet']),
  sticker('animal-bear', 'animals', 'Bear', '🐻', ['animal']),
  sticker('animal-panda', 'animals', 'Panda', '🐼', ['animal']),
  sticker('animal-fox', 'animals', 'Fox', '🦊', ['animal']),
  sticker('animal-lion', 'animals', 'Lion', '🦁', ['animal']),
  sticker('animal-tiger', 'animals', 'Tiger', '🐯', ['animal']),
  sticker('animal-monkey', 'animals', 'Monkey', '🐵', ['animal']),
  sticker('animal-frog', 'animals', 'Frog', '🐸', ['animal']),
  sticker('animal-penguin', 'animals', 'Penguin', '🐧', ['animal']),
  sticker('animal-owl', 'animals', 'Owl', '🦉', ['animal']),
  sticker('animal-butterfly', 'animals', 'Butterfly', '🦋', ['nature']),
  sticker('animal-bee', 'animals', 'Bee', '🐝', ['nature']),
  sticker('animal-fish', 'animals', 'Fish', '🐟', ['sea']),
  sticker('animal-whale', 'animals', 'Whale', '🐳', ['sea']),
  sticker('food-coffee', 'food', 'Coffee', '☕', ['drink', 'work']),
  sticker('food-tea', 'food', 'Tea', '🍵', ['drink']),
  sticker('food-water', 'food', 'Water', '💧', ['drink']),
  sticker('food-pizza', 'food', 'Pizza', '🍕', ['meal']),
  sticker('food-burger', 'food', 'Burger', '🍔', ['meal']),
  sticker('food-fries', 'food', 'Fries', '🍟', ['meal']),
  sticker('food-cake', 'food', 'Cake', '🍰', ['dessert']),
  sticker('food-donut', 'food', 'Donut', '🍩', ['dessert']),
  sticker('food-cookie', 'food', 'Cookie', '🍪', ['dessert']),
  sticker('food-apple', 'food', 'Apple', '🍎', ['fruit']),
  sticker('food-banana', 'food', 'Banana', '🍌', ['fruit']),
  sticker('food-strawberry', 'food', 'Strawberry', '🍓', ['fruit']),
  sticker('work-briefcase', 'work', 'Briefcase', '💼', ['job', 'business']),
  sticker('work-calendar', 'work', 'Calendar', '📅', ['schedule', 'date']),
  sticker('work-chart', 'work', 'Chart', '📊', ['analytics', 'report']),
  sticker('work-folder', 'work', 'Folder', '📁', ['files']),
  sticker('work-clipboard', 'work', 'Clipboard', '📋', ['tasks']),
  sticker('work-document', 'work', 'Document', '📄', ['file']),
  sticker('work-email', 'work', 'Email', '✉️', ['message']),
  sticker('work-phone', 'work', 'Phone', '☎️', ['call']),
  sticker('work-money', 'work', 'Money', '💰', ['business', 'finance']),
  sticker('work-clock', 'work', 'Clock', '🕒', ['time']),
  sticker('work-check', 'work', 'Completed', '✅', ['done', 'task']),
  sticker('work-pin', 'work', 'Location', '📍', ['place']),
  sticker('school-book', 'school', 'Book', '📖', ['read', 'study']),
  sticker('school-books', 'school', 'Books', '📚', ['read', 'study']),
  sticker('school-pencil', 'school', 'Pencil', '✏️', ['write']),
  sticker('school-pen', 'school', 'Pen', '🖊️', ['write']),
  sticker('school-ruler', 'school', 'Ruler', '📏', ['measure']),
  sticker('school-scissors', 'school', 'Scissors', '✂️', ['cut']),
  sticker('school-backpack', 'school', 'Backpack', '🎒', ['student']),
  sticker('school-cap', 'school', 'Graduation', '🎓', ['graduate']),
  sticker('school-microscope', 'school', 'Microscope', '🔬', ['science']),
  sticker('school-flask', 'school', 'Flask', '🧪', ['science']),
  sticker('school-calculator', 'school', 'Calculator', '🧮', ['math']),
  sticker('school-lightbulb', 'school', 'Idea', '💡', ['idea', 'learn']),
  sticker('tech-laptop', 'tech', 'Laptop', '💻', ['computer', 'code']),
  sticker('tech-desktop', 'tech', 'Desktop', '🖥️', ['computer']),
  sticker('tech-phone', 'tech', 'Smartphone', '📱', ['mobile']),
  sticker('tech-keyboard', 'tech', 'Keyboard', '⌨️', ['computer']),
  sticker('tech-mouse', 'tech', 'Mouse', '🖱️', ['computer']),
  sticker('tech-gear', 'tech', 'Gear', '⚙️', ['settings']),
  sticker('tech-tool', 'tech', 'Tool', '🔧', ['settings', 'repair']),
  sticker('tech-battery', 'tech', 'Battery', '🔋', ['power']),
  sticker('tech-plug', 'tech', 'Plug', '🔌', ['power']),
  sticker('tech-satellite', 'tech', 'Satellite', '🛰️', ['space']),
  sticker('tech-robot', 'tech', 'Robot', '🤖', ['ai']),
  sticker('tech-game', 'tech', 'Game Controller', '🎮', ['gaming']),
  sticker('travel-plane', 'travel', 'Airplane', '✈️', ['flight']),
  sticker('travel-car', 'travel', 'Car', '🚗', ['drive']),
  sticker('travel-bus', 'travel', 'Bus', '🚌', ['transport']),
  sticker('travel-train', 'travel', 'Train', '🚆', ['transport']),
  sticker('travel-ship', 'travel', 'Ship', '🚢', ['sea']),
  sticker('travel-bike', 'travel', 'Bike', '🚲', ['ride']),
  sticker('travel-map', 'travel', 'Map', '🗺️', ['location']),
  sticker('travel-compass', 'travel', 'Compass', '🧭', ['direction']),
  sticker('travel-luggage', 'travel', 'Luggage', '🧳', ['trip']),
  sticker('travel-camera', 'travel', 'Camera', '📷', ['photo']),
  sticker('travel-mountain', 'travel', 'Mountain', '🏔️', ['adventure']),
  sticker('travel-beach', 'travel', 'Beach', '🏖️', ['vacation']),
  sticker('weather-sunny', 'weather', 'Sunny', '☀️', ['sun']),
  sticker('weather-cloud', 'weather', 'Cloudy', '☁️', ['cloud']),
  sticker('weather-rain', 'weather', 'Rain', '🌧️', ['rain']),
  sticker('weather-storm', 'weather', 'Storm', '⛈️', ['thunder']),
  sticker('weather-snow', 'weather', 'Snow', '❄️', ['winter']),
  sticker('weather-wind', 'weather', 'Wind', '💨', ['windy']),
  sticker('weather-lightning', 'weather', 'Lightning', '⚡', ['storm']),
  sticker('weather-umbrella', 'weather', 'Umbrella', '☂️', ['rain']),
  sticker('weather-thermometer', 'weather', 'Temperature', '🌡️', ['hot', 'cold']),
  sticker('labels-important', 'labels', 'Important', 'IMPORTANT', ['priority', 'alert'], 120, 40),
  sticker('labels-urgent', 'labels', 'Urgent', 'URGENT', ['priority', 'alert'], 110, 40),
  sticker('labels-done', 'labels', 'Done', 'DONE', ['complete'], 90, 40),
  sticker('labels-todo', 'labels', 'To Do', 'TO DO', ['task'], 90, 40),
  sticker('labels-review', 'labels', 'Review', 'REVIEW', ['task'], 105, 40),
  sticker('labels-idea', 'labels', 'Idea', 'IDEA', ['idea'], 85, 40),
  sticker('labels-note', 'labels', 'Note', 'NOTE', ['note'], 85, 40),
  sticker('labels-reminder', 'labels', 'Reminder', 'REMINDER', ['reminder'], 120, 40),
  sticker('labels-approved', 'labels', 'Approved', 'APPROVED', ['yes'], 125, 40),
  sticker('labels-draft', 'labels', 'Draft', 'DRAFT', ['document'], 90, 40),
  sticker('pin-red', 'pins', 'Red Pin', '📌', ['pushpin', 'board']),
  sticker('pin-blue', 'pins', 'Blue Pin', '🔵', ['pin', 'board']),
  sticker('pin-green', 'pins', 'Green Pin', '🟢', ['pin', 'board']),
  sticker('pin-yellow', 'pins', 'Yellow Pin', '🟡', ['pin', 'board']),
  sticker('pin-purple', 'pins', 'Purple Pin', '🟣', ['pin', 'board']),
  sticker('pin-round', 'pins', 'Round Pin', '📍', ['pin', 'location']),
  sticker('pin-paperclip', 'pins', 'Paperclip', '📎', ['clip', 'paper']),
  sticker('pin-safety', 'pins', 'Safety Pin', '🧷', ['pin']),
  sticker('tape-cream', 'tape', 'Cream Tape', '▰', ['tape', 'paper'], 110, 34, [
    'notebook',
    'graph-board',
  ]),
  sticker('tape-yellow', 'tape', 'Yellow Tape', '▰', ['tape', 'yellow'], 110, 34, [
    'notebook',
    'graph-board',
  ]),
  sticker('tape-pink', 'tape', 'Pink Tape', '▰', ['tape', 'pink'], 110, 34, ['notebook']),
  sticker('tape-blue', 'tape', 'Blue Tape', '▰', ['tape', 'blue'], 110, 34, [
    'notebook',
    'blueprint',
  ]),
  sticker('tape-green', 'tape', 'Green Tape', '▰', ['tape', 'green'], 110, 34, [
    'notebook',
    'green-chalkboard',
  ]),
  sticker('doodle-lightbulb', 'doodles', 'Idea Doodle', '💡', ['idea', 'sketch']),
  sticker('doodle-cloud', 'doodles', 'Cloud Doodle', '☁', ['cloud', 'sketch']),
  sticker('doodle-sun', 'doodles', 'Sun Doodle', '☼', ['sun', 'sketch']),
  sticker('doodle-moon', 'doodles', 'Moon Doodle', '☾', ['moon', 'sketch']),
  sticker('doodle-flower', 'doodles', 'Flower Doodle', '❀', ['flower', 'sketch']),
  sticker('doodle-heart', 'doodles', 'Heart Doodle', '♡', ['heart', 'sketch']),
  sticker('doodle-star', 'doodles', 'Star Doodle', '☆', ['star', 'sketch']),
  sticker('doodle-smile', 'doodles', 'Smile Doodle', '☺', ['smile', 'sketch']),
  sticker('doodle-music', 'doodles', 'Music Doodle', '♪', ['music', 'sketch']),
  sticker('doodle-check', 'doodles', 'Check Doodle', '✓', ['check', 'sketch']),
  sticker('doodle-arrow', 'doodles', 'Arrow Doodle', '➜', ['arrow', 'sketch']),
  sticker('doodle-question', 'doodles', 'Question Doodle', '?', ['question', 'sketch']),
];
export const DEFAULT_DRAWING_STICKER_SIZE = 64;
export const MIN_DRAWING_STICKER_SIZE = 24;
export const MAX_DRAWING_STICKER_SIZE = 320;
export const DRAWING_STICKER_ROTATION_STEP = 15;
