import { DrawingBoardDefinition } from '../models/drawring-board.model';

export const DRAWING_BOARD_DEFINITIONS: DrawingBoardDefinition[] = [
  {
    type: 'whiteboard',
    name: 'Whiteboard',
    description: 'Clean board for markers, planning and quick sketches.',
    icon: 'fa-solid fa-pen',
    background: '#f7f7f3',
    surfaceClass: 'drawing-surface-whiteboard',
    tool: {
      type: 'marker',
      name: 'Marker',
      icon: 'fa-solid fa-pen',
      colors: [
        { id: 'black', name: 'Black', value: '#171717' },
        { id: 'blue', name: 'Blue', value: '#245edb' },
        { id: 'red', name: 'Red', value: '#e43d3d' },
        { id: 'green', name: 'Green', value: '#269653' },
        { id: 'orange', name: 'Orange', value: '#ee8b23' },
        { id: 'purple', name: 'Purple', value: '#8255c7' },
      ],
      sizes: [2, 4, 6, 9, 12],
      defaultColor: '#171717',
      defaultSize: 4,
      opacity: 0.94,
      cap: 'round',
    },
  },
  {
    type: 'blackboard',
    name: 'Blackboard',
    description: 'Classic dark board with colored chalk.',
    icon: 'fa-solid fa-chalkboard',
    background: '#242522',
    surfaceClass: 'drawing-surface-blackboard',
    tool: {
      type: 'chalk',
      name: 'Chalk',
      icon: 'fa-solid fa-pen',
      colors: [
        { id: 'white', name: 'White', value: '#f4f0df' },
        { id: 'yellow', name: 'Yellow', value: '#f1d96a' },
        { id: 'pink', name: 'Pink', value: '#e99ca9' },
        { id: 'blue', name: 'Blue', value: '#83b9df' },
        { id: 'green', name: 'Green', value: '#9dcd9a' },
      ],
      sizes: [3, 5, 7, 10, 14],
      defaultColor: '#f4f0df',
      defaultSize: 5,
      opacity: 0.82,
      cap: 'round',
    },
  },
  {
    type: 'green-chalkboard',
    name: 'Green Chalkboard',
    description: 'Traditional school-style green board with chalk.',
    icon: 'fa-solid fa-chalkboard',
    background: '#244c3a',
    surfaceClass: 'drawing-surface-green-chalkboard',
    tool: {
      type: 'chalk',
      name: 'Chalk',
      icon: 'fa-solid fa-pen',
      colors: [
        { id: 'white', name: 'White', value: '#f5f0df' },
        { id: 'yellow', name: 'Yellow', value: '#f2dc74' },
        { id: 'pink', name: 'Pink', value: '#efa3b3' },
        { id: 'blue', name: 'Blue', value: '#8bc5e5' },
        { id: 'orange', name: 'Orange', value: '#eab274' },
      ],
      sizes: [3, 5, 7, 10, 14],
      defaultColor: '#f5f0df',
      defaultSize: 5,
      opacity: 0.82,
      cap: 'round',
    },
  },
  {
    type: 'graph-board',
    name: 'Graph Board',
    description: 'Grid surface for diagrams, layouts and technical sketches.',
    icon: 'fa-solid fa-border-all',
    background: '#f5f6f5',
    surfaceClass: 'drawing-surface-graph',
    tool: {
      type: 'technical-pen',
      name: 'Technical Pen',
      icon: 'fa-solid fa-pen-nib',
      colors: [
        { id: 'black', name: 'Black', value: '#20252a' },
        { id: 'blue', name: 'Blue', value: '#2462ad' },
        { id: 'red', name: 'Red', value: '#c84545' },
        { id: 'green', name: 'Green', value: '#397b55' },
      ],
      sizes: [1, 2, 3, 5, 7],
      defaultColor: '#20252a',
      defaultSize: 2,
      opacity: 0.96,
      cap: 'round',
    },
  },
  {
    type: 'notebook',
    name: 'Notebook Paper',
    description: 'Ruled paper for handwriting, notes and rough sketches.',
    icon: 'fa-regular fa-file-lines',
    background: '#faf7ec',
    surfaceClass: 'drawing-surface-notebook',
    tool: {
      type: 'pen',
      name: 'Ink Pen',
      icon: 'fa-solid fa-pen-nib',
      colors: [
        { id: 'black', name: 'Black', value: '#262421' },
        { id: 'blue', name: 'Blue', value: '#2855a5' },
        { id: 'red', name: 'Red', value: '#c33e3e' },
        { id: 'green', name: 'Green', value: '#347249' },
      ],
      sizes: [1, 2, 3, 4, 6],
      defaultColor: '#2855a5',
      defaultSize: 2,
      opacity: 0.96,
      cap: 'round',
    },
  },
  {
    type: 'blueprint',
    name: 'Blueprint',
    description: 'Technical blueprint surface for plans and structured drawings.',
    icon: 'fa-solid fa-ruler-combined',
    background: '#164d78',
    surfaceClass: 'drawing-surface-blueprint',
    tool: {
      type: 'technical-pen',
      name: 'Technical Pen',
      icon: 'fa-solid fa-pen-ruler',
      colors: [
        { id: 'white', name: 'White', value: '#edf6f7' },
        { id: 'cyan', name: 'Cyan', value: '#8dd9e7' },
        { id: 'yellow', name: 'Yellow', value: '#f1dc78' },
        { id: 'pink', name: 'Pink', value: '#e9a7bd' },
      ],
      sizes: [1, 2, 3, 5, 7],
      defaultColor: '#edf6f7',
      defaultSize: 2,
      opacity: 0.94,
      cap: 'round',
    },
  },
];
export const DEFAULT_DRAWING_BOARD_TYPE = 'whiteboard' as const;
export const DEFAULT_DRAWING_BOARD_WIDTH = 1200;
export const DEFAULT_DRAWING_BOARD_HEIGHT = 760;
