import { NotePinModel } from '../models/note-pin.model';

export const NOTE_PINS: NotePinModel[] = [
  {
    id: 'red-pin',
    name: 'Classic Red',
    type: 'pushpin',
    color: '#e53945',
    secondaryColor: '#a91f2b',
    rotation: -8,
  },
  {
    id: 'blue-pin',
    name: 'Classic Blue',
    type: 'pushpin',
    color: '#2685e8',
    secondaryColor: '#1257a4',
    rotation: 7,
  },
  {
    id: 'green-pin',
    name: 'Classic Green',
    type: 'pushpin',
    color: '#2ebd7b',
    secondaryColor: '#147449',
    rotation: -5,
  },
  {
    id: 'yellow-pin',
    name: 'Classic Yellow',
    type: 'pushpin',
    color: '#f4ba28',
    secondaryColor: '#b77d0a',
    rotation: 6,
  },
  {
    id: 'white-pin',
    name: 'Classic White',
    type: 'pushpin',
    color: '#ecebea',
    secondaryColor: '#aaa8a4',
    rotation: -4,
  },
  {
    id: 'black-pin',
    name: 'Classic Black',
    type: 'pushpin',
    color: '#26272b',
    secondaryColor: '#08090b',
    rotation: 7,
  },
  {
    id: 'gold-round',
    name: 'Round Gold',
    type: 'round-pin',
    color: '#f0b522',
    secondaryColor: '#9d6710',
    rotation: -4,
  },
  {
    id: 'silver-round',
    name: 'Round Silver',
    type: 'round-pin',
    color: '#d9dadd',
    secondaryColor: '#7e8288',
    rotation: 4,
  },
  {
    id: 'wood-pin',
    name: 'Wooden',
    type: 'round-pin',
    color: '#bb7c42',
    secondaryColor: '#70401f',
    rotation: -6,
  },
  {
    id: 'dark-wood-pin',
    name: 'Wooden Dark',
    type: 'round-pin',
    color: '#74431f',
    secondaryColor: '#3c2110',
    rotation: 5,
  },
  {
    id: 'heart-red',
    name: 'Heart Red',
    type: 'heart',
    color: '#ef3545',
    secondaryColor: '#a81725',
    icon: 'fa-solid fa-heart',
    rotation: -6,
  },
  {
    id: 'heart-pink',
    name: 'Heart Pink',
    type: 'heart',
    color: '#f477a7',
    secondaryColor: '#bf3c70',
    icon: 'fa-solid fa-heart',
    rotation: 5,
  },
  {
    id: 'heart-purple',
    name: 'Heart Purple',
    type: 'heart',
    color: '#9a59e5',
    secondaryColor: '#5e2aa2',
    icon: 'fa-solid fa-heart',
    rotation: -4,
  },
  {
    id: 'star-gold',
    name: 'Star Gold',
    type: 'star',
    color: '#f1bd30',
    secondaryColor: '#ad760c',
    icon: 'fa-solid fa-star',
    rotation: -6,
  },
  {
    id: 'star-blue',
    name: 'Star Blue',
    type: 'star',
    color: '#4099e9',
    secondaryColor: '#1b5da0',
    icon: 'fa-solid fa-star',
    rotation: 5,
  },
  {
    id: 'star-pink',
    name: 'Star Pink',
    type: 'star',
    color: '#ef76a6',
    secondaryColor: '#b93e70',
    icon: 'fa-solid fa-star',
    rotation: -5,
  },
  {
    id: 'flower-white',
    name: 'Flower White',
    type: 'flower',
    color: '#f5f4ec',
    secondaryColor: '#e0a91c',
    icon: 'fa-solid fa-fan',
    rotation: 3,
  },
  {
    id: 'flower-pink',
    name: 'Flower Pink',
    type: 'flower',
    color: '#ee72a5',
    secondaryColor: '#e8b31b',
    icon: 'fa-solid fa-fan',
    rotation: -6,
  },
  {
    id: 'flower-purple',
    name: 'Flower Purple',
    type: 'flower',
    color: '#a960dc',
    secondaryColor: '#f0bb24',
    icon: 'fa-solid fa-fan',
    rotation: 5,
  },
  {
    id: 'flower-yellow',
    name: 'Flower Yellow',
    type: 'flower',
    color: '#f0c13a',
    secondaryColor: '#a9780a',
    icon: 'fa-solid fa-fan',
    rotation: -3,
  },
  {
    id: 'flag-red',
    name: 'Flag Red',
    type: 'flag',
    color: '#e33d43',
    secondaryColor: '#8b2026',
    rotation: -4,
  },
  {
    id: 'flag-blue',
    name: 'Flag Blue',
    type: 'flag',
    color: '#2f8ade',
    secondaryColor: '#155392',
    rotation: 4,
  },
  {
    id: 'flag-green',
    name: 'Flag Green',
    type: 'flag',
    color: '#32ad70',
    secondaryColor: '#186c46',
    rotation: -3,
  },
  {
    id: 'flag-yellow',
    name: 'Flag Yellow',
    type: 'flag',
    color: '#ecb62e',
    secondaryColor: '#986c0c',
    rotation: 4,
  },
  {
    id: 'triangle-red',
    name: 'Triangle Red',
    type: 'triangle',
    color: '#ea4b4b',
    secondaryColor: '#a12121',
    rotation: -4,
  },
  {
    id: 'triangle-blue',
    name: 'Triangle Blue',
    type: 'triangle',
    color: '#418fd9',
    secondaryColor: '#1a5891',
    rotation: 4,
  },
  {
    id: 'triangle-green',
    name: 'Triangle Green',
    type: 'triangle',
    color: '#4bc277',
    secondaryColor: '#24794a',
    rotation: -5,
  },
  {
    id: 'triangle-yellow',
    name: 'Triangle Yellow',
    type: 'triangle',
    color: '#f1bd39',
    secondaryColor: '#a27613',
    rotation: 5,
  },
  {
    id: 'circle-red',
    name: 'Circle Red',
    type: 'circle',
    color: '#e95432',
    secondaryColor: '#a52b16',
    rotation: 0,
  },
  {
    id: 'circle-blue',
    name: 'Circle Blue',
    type: 'circle',
    color: '#438dcc',
    secondaryColor: '#215789',
    rotation: 0,
  },
  {
    id: 'circle-green',
    name: 'Circle Green',
    type: 'circle',
    color: '#45b96d',
    secondaryColor: '#287645',
    rotation: 0,
  },
  {
    id: 'circle-yellow',
    name: 'Circle Yellow',
    type: 'circle',
    color: '#eab838',
    secondaryColor: '#9d7416',
    rotation: 0,
  },
  {
    id: 'smiley',
    name: 'Smiley Face',
    type: 'face',
    color: '#f2c63d',
    secondaryColor: '#3d3522',
    icon: 'fa-solid fa-face-smile',
    rotation: -4,
  },
  {
    id: 'sad-face',
    name: 'Sad Face',
    type: 'face',
    color: '#64a7df',
    secondaryColor: '#233b50',
    icon: 'fa-solid fa-face-frown',
    rotation: 4,
  },
  {
    id: 'coffee-bean',
    name: 'Coffee Bean',
    type: 'coffee',
    color: '#78462b',
    secondaryColor: '#3d2318',
    rotation: -12,
  },
  {
    id: 'leaf-pin',
    name: 'Leaf',
    type: 'leaf',
    color: '#559746',
    secondaryColor: '#285e27',
    icon: 'fa-solid fa-leaf',
    rotation: -12,
  },
  {
    id: 'acorn-pin',
    name: 'Acorn',
    type: 'acorn',
    color: '#9b612c',
    secondaryColor: '#5c3519',
    rotation: 6,
  },
  {
    id: 'bubble-pin',
    name: 'Bubble',
    type: 'bubble',
    color: '#b8e8f8',
    secondaryColor: '#706de1',
    rotation: 0,
  },
  {
    id: 'crystal-pin',
    name: 'Crystal',
    type: 'crystal',
    color: '#9a55da',
    secondaryColor: '#e6b8ff',
    icon: 'fa-solid fa-gem',
    rotation: -5,
  },
  {
    id: 'diamond-pin',
    name: 'Diamond',
    type: 'diamond',
    color: '#dfeef6',
    secondaryColor: '#7599b7',
    icon: 'fa-regular fa-gem',
    rotation: 6,
  },
  {
    id: 'masking-tape',
    name: 'Masking Tape',
    type: 'tape',
    color: '#d7c4a2',
    secondaryColor: '#b09d7c',
    rotation: -5,
    pattern: 'plain',
  },
  {
    id: 'washi-tape',
    name: 'Washi Tape',
    type: 'tape',
    color: '#ed779b',
    secondaryColor: '#f2b4c8',
    rotation: 4,
    pattern: 'stripe',
  },
  {
    id: 'polka-tape',
    name: 'Polka Tape',
    type: 'tape',
    color: '#8ab9df',
    secondaryColor: '#e6f1fa',
    rotation: -4,
    pattern: 'dots',
  },
  {
    id: 'grid-tape',
    name: 'Grid Tape',
    type: 'tape',
    color: '#e7e0cf',
    secondaryColor: '#8f969e',
    rotation: 3,
    pattern: 'grid',
  },
  {
    id: 'floral-tape',
    name: 'Floral Tape',
    type: 'tape',
    color: '#efe4d7',
    secondaryColor: '#dc7690',
    rotation: -3,
    pattern: 'floral',
  },
  {
    id: 'paperclip',
    name: 'Paper Clip',
    type: 'paperclip',
    color: '#a8adb3',
    secondaryColor: '#676c72',
    icon: 'fa-solid fa-paperclip',
    rotation: 8,
  },
  {
    id: 'pink-paperclip',
    name: 'Pink Clip',
    type: 'paperclip',
    color: '#ee77a4',
    secondaryColor: '#ae3c68',
    icon: 'fa-solid fa-paperclip',
    rotation: -7,
  },
  {
    id: 'gold-paperclip',
    name: 'Gold Clip',
    type: 'paperclip',
    color: '#d6a328',
    secondaryColor: '#896413',
    icon: 'fa-solid fa-paperclip',
    rotation: 7,
  },
  {
    id: 'black-paperclip',
    name: 'Black Clip',
    type: 'paperclip',
    color: '#25272d',
    secondaryColor: '#060709',
    icon: 'fa-solid fa-paperclip',
    rotation: -6,
  },
  {
    id: 'rose-paperclip',
    name: 'Rose Clip',
    type: 'paperclip',
    color: '#e58aa1',
    secondaryColor: '#9b4b61',
    icon: 'fa-solid fa-paperclip',
    rotation: 6,
  },
  {
    id: 'none',
    name: 'No Pin',
    type: 'none',
    color: 'transparent',
    rotation: 0,
  },
];

export const DEFAULT_NOTE_PIN_ID = 'red-pin';
